[loggers]
keys=root,main,mainfile

[handlers]
keys=console,file

[formatters]
keys=full

[logger_root]
level=FATAL
handlers=console

[logger_main]
level=DEBUG
handlers=console
propagate=0
qualname=main

[logger_mainfile]
level=DEBUG
handlers=file
propagate=1
qualname=main.file

[handler_console]
class=StreamHandler
level=DEBUG
formatter=full
args=(sys.stdout,)

[handler_file]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=full
args=('server.log','w',10485760,)

[formatter_full]
format=%(asctime)s %(threadName)s %(levelname)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S,%03d
style=%
validate=True
class=logging.Formatter
