# Form implementation generated from reading ui file './roboter/gui/gui_layout.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.getRobotPositionButton = QtWidgets.QPushButton(
            parent=self.centralwidget
        )
        self.getRobotPositionButton.setGeometry(QtCore.QRect(20, 90, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.getRobotPositionButton.setFont(font)
        self.getRobotPositionButton.setAcceptDrops(True)
        self.getRobotPositionButton.setAutoFillBackground(False)
        self.getRobotPositionButton.setObjectName("getRobotPositionButton")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 140, 1240, 560))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(176)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.helpLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.helpLabel.setGeometry(QtCore.QRect(20, 10, 771, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.helpLabel.setFont(font)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.errorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(350, 84, 901, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(192, 28, 40);")
        self.errorLabel.setObjectName("errorLabel")
        self.clearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(180, 90, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robopro Terminal"))
        self.getRobotPositionButton.setText(
            _translate("MainWindow", "Get robot position")
        )
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "x (m)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "y (m)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "z (m)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Psi (rad)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Theta (rad)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Phi (rad)"))
        self.helpLabel.setText(
            _translate(
                "MainWindow",
                'To get robot end effector position press button "Get robot position". To clear table press "Clear table". Note that the angle values are given for the Euler angles with the ZYX transformation.',
            )
        )
        self.errorLabel.setText(_translate("MainWindow", "Error"))
        self.clearButton.setText(_translate("MainWindow", "Clear table"))
